### ISSUE TITLE
Release error

### ISSUE THREAD

**Issue by superstrongbozo** [Test-Account666/LethalCompany-ControlCompanyAddons#2]
when i release old bird, spawns 2 old birds instead of 1, can i fix this?

**Comment by Test-Account666** [comment]
Looks like a ControlCompany bug.

When exiting the old bird, it takes a while before it despawns

**Comment by Test-Account666** [comment]
So... This seems to be a feature of ControlCompany...

The old bird will only despawn after 3 seconds.


This is probably due to missiles possibly existing.

It is not optimal, but I now "fixed" this by removing the waiting time and just hiding exceptions thrown by the missile.

I'm just unsure if clients will still throw errors...

Please notify me when issues arise
